/** 

  Ground Station Main
  
  Written by Nick McComb
  May 2016
  
**/

//#ifndef MAIN_H_
//#define MAIN_H_

#include "project_header.h"

//RSSI Interpret Settings
#define RSSI_READ_TIMEOUT 10000 //uS
#define RSSI_DEBOUNCE_DELAY 20   //uS

//Function Prototypes

//static uint8_t ReadCalibrationByte( uint8_t index );
void processRSSI();
void outputSignalStrength(uint8_t str); //Accepts 0, 1, 2, or 3

//usart
extern void SendStringPC(char *stufftosend);
extern void SendStringPC(const char stufftosend[]);
extern void SendCharPC(char charToSend);
extern void SendCharONOFF(char charToSend);
extern void SendNumPC(uint8_t numToSend);
extern void SendNumPC(uint16_t numToSend);
extern void SendNumPC(int16_t numToSend);
extern void SendNumPC(uint64_t numToSend);
extern void SendFloatPC(double numToSend);

/* Global Variables */
extern uint8_t DeviceSignature[11];
extern uint64_t UC_LOT_NUMBER;		//Contains a number genrated by the lot number
extern uint64_t UC_WAFER_ID;		//Contains a number generated by the wafer position
extern int16_t serialNumber;		//Creates an OMG Custom Serial number, ref. https://goo.gl/15qd7k



//#endif /* MAIN_H_ */